name: NextJs CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: eletrico123/grazionale-cv
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        instance-ids: ${{ secrets.INSTANCE_ID }}
        working-directory: /home/ubuntu
        command: sudo docker run --name grazionale-cv -d -p 80:3000 eletrico123/grazionale-cv:master-b3848d1

